/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajofinal1215;

/**
 *
 * @author felipe
 */
public class Vendedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vendedor
     */
    public Vendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jprincipal = new javax.swing.JTabbedPane();
        jPanelDC = new javax.swing.JPanel();
        jcodCliente = new javax.swing.JLabel();
        jnombre = new javax.swing.JLabel();
        japellidoMat = new javax.swing.JLabel();
        japellidoPat = new javax.swing.JLabel();
        txtcodCliente = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellidoMat = new javax.swing.JTextField();
        txtapellidoPat = new javax.swing.JTextField();
        jPanelDV = new javax.swing.JPanel();
        jcodVehiculo = new javax.swing.JLabel();
        jmarca = new javax.swing.JLabel();
        jmodelo = new javax.swing.JLabel();
        jcolor = new javax.swing.JLabel();
        jprecio = new javax.swing.JLabel();
        txtcodVehiculo = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        jCBcolor = new javax.swing.JComboBox();
        txtprecio = new javax.swing.JTextField();
        jPanelF = new javax.swing.JPanel();
        jcodFactura = new javax.swing.JLabel();
        jfechaCompra = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcodVehiculo2 = new javax.swing.JLabel();
        jestado = new javax.swing.JLabel();
        txtcodFactura = new javax.swing.JTextField();
        txtfechaCompra = new javax.swing.JTextField();
        txtcodCliente2 = new javax.swing.JTextField();
        txtcodVehiculo2 = new javax.swing.JTextField();
        jCBestado = new javax.swing.JComboBox();
        jPanelA = new javax.swing.JPanel();
        jseleccioanrA = new javax.swing.JLabel();
        jCBseleccionarA = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("INGRESAR DATOS");

        jprincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("PRINCIPAL"));

        jcodCliente.setText("Código Cliente:");

        jnombre.setText("Nombre:");

        japellidoMat.setText("Apellido Materno:");

        japellidoPat.setText("Apellido Paterno:");

        javax.swing.GroupLayout jPanelDCLayout = new javax.swing.GroupLayout(jPanelDC);
        jPanelDC.setLayout(jPanelDCLayout);
        jPanelDCLayout.setHorizontalGroup(
            jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDCLayout.createSequentialGroup()
                        .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcodCliente)
                            .addComponent(jnombre))
                        .addGap(29, 29, 29)
                        .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcodCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtnombre)))
                    .addGroup(jPanelDCLayout.createSequentialGroup()
                        .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(japellidoPat)
                            .addComponent(japellidoMat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtapellidoMat)
                            .addComponent(txtapellidoPat))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDCLayout.setVerticalGroup(
            jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcodCliente)
                    .addComponent(txtcodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(japellidoMat)
                    .addComponent(txtapellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(japellidoPat)
                    .addComponent(txtapellidoPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jprincipal.addTab("DATOS CLIENTES", jPanelDC);

        jcodVehiculo.setText("Código Vehículo:");

        jmarca.setText("Marca:");

        jmodelo.setText("Modelo:");

        jcolor.setText("Color:");

        jprecio.setText("Precio:");

        jCBcolor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BLANCO", "NEGRO", "ROJO", "AZUL" }));

        javax.swing.GroupLayout jPanelDVLayout = new javax.swing.GroupLayout(jPanelDV);
        jPanelDV.setLayout(jPanelDVLayout);
        jPanelDVLayout.setHorizontalGroup(
            jPanelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcodVehiculo)
                    .addComponent(jmarca)
                    .addComponent(jmodelo)
                    .addComponent(jcolor)
                    .addComponent(jprecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcodVehiculo)
                    .addComponent(txtmarca)
                    .addComponent(txtmodelo)
                    .addComponent(jCBcolor, 0, 150, Short.MAX_VALUE)
                    .addComponent(txtprecio))
                .addContainerGap(456, Short.MAX_VALUE))
        );
        jPanelDVLayout.setVerticalGroup(
            jPanelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcodVehiculo)
                    .addComponent(txtcodVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmarca)
                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmodelo)
                    .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcolor)
                    .addComponent(jCBcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jprecio)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jprincipal.addTab("DATOS VEHÍCULOS", jPanelDV);

        jcodFactura.setText("Código Factura:");

        jfechaCompra.setText("Fecha Compra:");

        jLabel3.setText("Código Cliente:");

        jcodVehiculo2.setText("Código Vehículo:");

        jestado.setText("Estado:");

        jCBestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PENDIENTE", "PREPARADO", "ENTREGADO" }));

        javax.swing.GroupLayout jPanelFLayout = new javax.swing.GroupLayout(jPanelF);
        jPanelF.setLayout(jPanelFLayout);
        jPanelFLayout.setHorizontalGroup(
            jPanelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfechaCompra)
                    .addComponent(jLabel3)
                    .addComponent(jcodVehiculo2)
                    .addComponent(jcodFactura)
                    .addComponent(jestado))
                .addGap(18, 18, 18)
                .addGroup(jPanelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcodFactura)
                    .addComponent(txtfechaCompra)
                    .addComponent(txtcodCliente2)
                    .addComponent(txtcodVehiculo2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jCBestado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jPanelFLayout.setVerticalGroup(
            jPanelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcodFactura)
                    .addComponent(txtcodFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfechaCompra)
                    .addComponent(txtfechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcodCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcodVehiculo2)
                    .addComponent(txtcodVehiculo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jestado)
                    .addComponent(jCBestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jprincipal.addTab("FACTURA", jPanelF);

        jseleccioanrA.setText("Seleccionar Accesorio:");

        jCBseleccionarA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Accesorio", "Descripciión", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanelALayout = new javax.swing.GroupLayout(jPanelA);
        jPanelA.setLayout(jPanelALayout);
        jPanelALayout.setHorizontalGroup(
            jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jseleccioanrA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelALayout.createSequentialGroup()
                        .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jCBseleccionarA, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 174, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelALayout.setVerticalGroup(
            jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelALayout.createSequentialGroup()
                        .addComponent(jseleccioanrA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBseleccionarA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jprincipal.addTab("ACCESORIOS", jPanelA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JComboBox jCBcolor;
    public static javax.swing.JComboBox jCBestado;
    public static javax.swing.JComboBox jCBseleccionarA;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JPanel jPanelA;
    public static javax.swing.JPanel jPanelDC;
    public static javax.swing.JPanel jPanelDV;
    public static javax.swing.JPanel jPanelF;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JLabel japellidoMat;
    public static javax.swing.JLabel japellidoPat;
    public static javax.swing.JLabel jcodCliente;
    public static javax.swing.JLabel jcodFactura;
    public static javax.swing.JLabel jcodVehiculo;
    public static javax.swing.JLabel jcodVehiculo2;
    public static javax.swing.JLabel jcolor;
    public static javax.swing.JLabel jestado;
    private javax.swing.JLabel jfechaCompra;
    public static javax.swing.JLabel jmarca;
    private javax.swing.JLabel jmodelo;
    public static javax.swing.JLabel jnombre;
    public static javax.swing.JLabel jprecio;
    public static javax.swing.JTabbedPane jprincipal;
    public static javax.swing.JLabel jseleccioanrA;
    public static javax.swing.JTextField txtapellidoMat;
    public static javax.swing.JTextField txtapellidoPat;
    public static javax.swing.JTextField txtcodCliente;
    public static javax.swing.JTextField txtcodCliente2;
    public static javax.swing.JTextField txtcodFactura;
    public static javax.swing.JTextField txtcodVehiculo;
    private javax.swing.JTextField txtcodVehiculo2;
    public static javax.swing.JTextField txtfechaCompra;
    public static javax.swing.JTextField txtmarca;
    public static javax.swing.JTextField txtmodelo;
    public static javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
